language: node_js
node_js:
  - '0.12'
sudo: required
install:
  - npm install intern
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "wget http://goo.gl/qTy1IB"
    - "java -jar selenium-server-standalone-2.52.0.jar > /dev/null &"
    - sleep 15
script: ./node_modules/.bin/intern-runner config=tests/intern
